# Site settings
title: WCPAEZ BLOG
email: wcpaez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog about Angular, Ruby on Rails, Vim, TDD and others.
location: 'Lima, Perú.'  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" 
twitter_username: chences
github_username:  wcpaez

# Build settings
markdown: kramdown
