# Site settings
title: WCPAEZ BLOG | Sharing what I learned 
email: wcpaez@gmail.com
description: Personal blog about every stuff that I'm doing every day on my development career. Just want to share what I learned.
keywords: Wenceslao, Paez, Ruby on Rails, Rails, TDD, Rspec, Angular, Testing, Design Patterns, Capybara, Git
location: 'Lima, Perú.'  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" 
twitter_username: chences
github_username:  wcpaez

# Build settings
markdown: kramdown
